apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jmmaster
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /report
              name: jmeter-data-dir
          env:
            - name: MODE
              value: "MASTER"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/bash"]
          args: ["-c", "trap 'exit 0' SIGUSR1 && while true; do sleep 30;done"]
          ports:
            - containerPort: 60000
          livenessProbe:
            exec:
              command:
                - cat
                - /opt/jmeter/apache-jmeter/bin/jmeter
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - cat
                - /opt/jmeter/apache-jmeter/bin/jmeter
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.master | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: jmeter-data-dir-pvc
